version: "1.0"
services:
#? Configuracion DB MySQL
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hydrometrics
    restart: always
    networks:
      - hydrometrics-net
  # ? Configuracion Back
  hydrometrics-back:
    container_name: hydrometrics-back
    build:
     context: ./hydrometrics-main-back/
     dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: hydrometrics
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - hydrometrics-net
    depends_on:
      - mysql
    restart: always
  # ? Configuracion Front
  meteodata:
    container_name: meteodata
    build:
     context: ./hydrometric-front/
     dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    networks:
      - hydrometrics-net
    depends_on:
      - hydrometrics-back
    restart: always
networks:
  hydrometrics-net:
    name: hydrometrics-net





